### ISSUE TITLE
package missing from npm registry

### ISSUE THREAD

**Issue by codesmax** [mozilla/scanjs#166]
Up until a few days ago, the module was available on the public npm registry under the name 'mozilla/scanjs'. Now it's gone. Was this pulled intentionally? Will this be republished to the registry?

Thanks,
Max

**Comment by cphoton** [comment]
Hi, I noticed that there is a [module on npm](https://www.npmjs.com/package/secscan/) for the library, is that the official one? if not, is it reasonable to expect an official one in the short term?

**Comment by pauljt** [comment]
I don’t know who slalom digital but is not related to us afaik.  To be honest, I hadn’t really considered making an npm module since the tool was intended to be run in the browser, but we could do I suppose.

@freddyb thoughts?

**Comment by cphoton** [comment]
If the module were to be available on npm, it would make it easier to integrate it into build tools, for instance one could make something similar as [gulp-jshint](https://github.com/spalger/gulp-jshint).

**Comment by mozfreddyb** [comment]
Well the scanning bits could surely run in nodejs, without all the browser stuff.
I'll try to get #158 done soonish and will submit an official package afterwards.

(Sorry for the late response, was out of office last week)

**Comment by cphoton** [comment]
Thank you Frederick, no problem!
